---
title: KAZUSHIGE MATSUDA
format:
  pdf:
    documentclass: article
    geometry: margin=1in
    fontsize: 11pt
execute:
  echo: false
---

Keio University, 2-15-45 Mita Minato-ku, Tokyo, Japan 108-8345  
Web page: https://kmatsuda723.github.io/  
Email: kazu.matsuda@keio.jp

## Employment

- 2023-present: Associate Professor, Keio University
- 2021-2023: Tenure-Track Associate Professor, Graduate School of Economics, Kobe University
- 2019-2021: Assistant Professor, Graduate School of Economics, Hitotsubashi University

## Visiting Positions

- 2024: Visiting Fellow, European University Institute

## Education

- 2019: Ph.D. Economics, Princeton University (advisor: Richard Rogerson)
- 2013: M.A. Economics, University of Tokyo
- 2011: B.A. Economics, University of Tokyo

## Published Journal Articles

- [University Research and the Market for Higher Education](https://damiencapelle.com/wp-content/uploads/2025/04/ACM_2025.pdf) (2026), *American Economic Journal: Macroeconomics*
  with Titan Alon and Damien Capelle
- [Progressive Taxation versus College Subsidies with College Dropout](https://onlinelibrary.wiley.com/doi/10.1111/jmcb.12989) (2024), *Journal of Money, Credit, and Banking*
- [College Education and Income Contingent Loans in Equilibrium](https://drive.google.com/file/d/16YNfXzKAmdkJBV7BMQr-Z-pDTaAzGgMR/view) (2022), *Journal of Monetary Economics*
  with Karol Mazur
- [Optimal Timing of College Subsidies: Enrollment, Graduation, and the Skill Premium](https://www.sciencedirect.com/science/article/abs/pii/S001429212030180X) (2020), *European Economic Review*

## Working Papers

- [Spatial Misallocation in Education: The Left-Behind and Land Reforms in China](https://drive.google.com/file/d/1nzuZTDHmkbnsTxh0w-IXWzrHURzxIFSX/view)
  with Karol Mazur and Chao Shen
- [The Great Gatsby Goes to College: Tuition, Inequality, and Intergenerational Mobility](https://damiencapelle.com/wp-content/uploads/2026/05/Capelle-Matsuda-The-Great-Gatsby-May-2026.pdf)
  with Damien Capelle
- Alumni as Assets: Legacy Preferences and Donations in a Dynamic Model of Elite Colleges
  with Damien Capelle and Alexander Monge-Naranjo

## Conference Presentations

Society for Economic Dynamics 2022, Seventh Annual CIGS End of Year Macroeconomics Conference 2022, European Winter Meetings of the Econometric Society 2022, European Winter Meetings of the Econometric Society, Winter School 2020, 15th Annual Conference Warsaw International Economic Meeting 2020, CIGS Conference on Macroeconomic Theory and Policy 2019

## Refereeing Services

American Economic Journal: Macroeconomics, Review of Economic Dynamics, International Economic Review, The B.E. Journal of Macroeconomics, Journal of the Japanese and International Economies, Japanese Economic Review
